language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bcbowen/docker-react -f frontend/Dockerfile.dev .

script:
  - docker run -e CI=true bcbowen/docker-react npm run test
